In [59]:
import numpy as np

rand_vect = np.random.randint(1,20, size=15)  #generating random integer vector of size 15

print(rand_vect)

[16  9  1  5  6 15 11 15 13 17  3  2 18  3 17]


In [60]:
rand_vect = rand_vect.reshape((3,5))             # reshaping the vector into 3 by 5 array

print(rand_vect.shape)                           # getting size of the array

for i in range(rand_vect.shape[0]):
    rand_vect[i][np.argmax(rand_vect[i])] = 0    # replacing max of every row with '0'

print(rand_vect)

(3, 5)
[[ 0  9  1  5  6]
 [15 11 15 13  0]
 [ 3  2  0  3 17]]


In [61]:
array_2d = np.array([[4,1,7],[10,5,2],[8,3,9],[12,-1,6]]) # creating a 2d array of 4 by 3 shape

print(array_2d.shape)
print(type(array_2d))
print(array_2d.dtype)

(4, 3)
<class 'numpy.ndarray'>
int32


In [62]:
arr = np.array([[3,-2],[1,0]]) # intializing array

eig_val, eig_vec = np.linalg.eig(arr) # getting Eigen values and Eigen vectors of given array

print("Array: \n",arr)
print("Eigen values of array: \n",eig_val)
print("Eigen vectors of array: \n",eig_vec)

Array: 
 [[ 3 -2]
 [ 1  0]]
Eigen values of array: 
 [2. 1.]
Eigen vectors of array: 
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [63]:
array = np.array ([[0,1,2],[3,4,5]])

print(np.trace(array)) # getting sum of diagonal elements

4


In [64]:
a= np.array([[1,2],[3,4],[5,6]])    # intializing array 
print(a)

a = a.reshape((2,3))                #reshaping the array
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
